export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SERVER_ERROR = "SET_SERVER_ERROR";
export const SET_API_ERROR = "SET_API_ERROR";
export const SET_EVENTS = "SET_EVENTS";
export const UPDATE_EVENT_IN_EVENTS = "UPDATE_EVENT_IN_EVENTSV";
export const ADD_EVENT_TO_EVENTS = "ADD_EVENT_TO_EVENTS";
